Upgrade dependencies and migrate to zimscraperlib 3.3.2
openzim/youtube pull request #202
Opened 2024-05-18 13:20 UTC by dan-niles

### Changes
- Migrate to zimscraperlib 3.3.2
- Upgrade Python dependencies, including migration to Python 3.12
- Validate ZIM metadata (tags, title, description, long_description) as early as possible
- Added new CLI arguments: `long_description` and `disable_metadata_check`
- Added `disable_metadata_check` to `playlist mode`

Fix #175
Fix #188

2024-05-21 08:09 UTC, benoit74 requested changes
This is very good work, thank you!

Please add support for `long_description` in the `playlists` mode as well, not sure it is very valuable but at least we have it available, and it is mostly straightforward AFAIK:
- add arg to https://github.com/openzim/youtube/blob/main/src/youtube2zim/playlists/entrypoint.py
- update list at https://github.com/openzim/youtube/blob/d930c98a7a5247dba5a04ea2054888e44de9bcf2/src/youtube2zim/playlists/scraper.py#L142
- do not forgot update list at https://github.com/openzim/youtube/blob/d930c98a7a5247dba5a04ea2054888e44de9bcf2/src/youtube2zim/playlists/entrypoint.py#L78 to raise exception if `--long-description` is passed instead of `--playlists-long-description`

Few inline comments also indicate more minor changes needed.

Glad you achieved to make it worked properly without any help, it wasn't an easy thing ^^

2024-05-21 15:42 UTC, dan-niles commented on openzim.toml
> +source="https://github.com/videojs/video.js/releases/download/v7.8.1/video-js-7.8.1.zip"
Changed in [76da367](https://github.com/openzim/youtube/pull/202/commits/76da3679a7b33284f940e644f255212595400042)

2024-05-21 15:43 UTC, dan-niles commented on openzim.toml
> +source="https://code.jquery.com/jquery-3.5.1.min.js"
Changed in [76da367](https://github.com/openzim/youtube/pull/202/commits/76da3679a7b33284f940e644f255212595400042)

2024-05-21 15:43 UTC, dan-niles commented on openzim.toml
> +source="https://unpkg.com/webp-hero@0.0.0-dev.26/dist-cjs/polyfills.js"
Changed in [76da367](https://github.com/openzim/youtube/pull/202/commits/76da3679a7b33284f940e644f255212595400042)

2024-05-21 15:43 UTC, dan-niles commented on openzim.toml
> +source="https://unpkg.com/webp-hero@0.0.0-dev.26/dist-cjs/webp-hero.bundle.js"
Changed in [76da367](https://github.com/openzim/youtube/pull/202/commits/76da3679a7b33284f940e644f255212595400042)

2024-05-21 15:43 UTC, dan-niles commented on pyproject.toml
>    "MarkupSafe==2.0.1",           # jinja2 dependency (https://github.com/pallets/markupsafe/issues/284)
Removed in [7d66802](https://github.com/openzim/youtube/pull/202/commits/7d668023b6f45eab6fa0142dd419791ee4dcfd65)

2024-05-22 06:54 UTC, benoit74 approved these changes
LGTM, thank you!

2024-05-22 06:55 UTC, merged