Add Video player page
openzim/youtube pull request #229
Opened 2024-06-18 04:38 UTC by dan-niles

This PR adds the video player for the new UI.
- Set up video.js with support for subtitles and variable playback rates.
- Added `channel_description` and `channel_joined_date` to the `Author` schema so that we can display channel information easily in the video player page.
- Included `webp-hero` for WebP support in unsupported browsers.

Closes #215
Closes #174

2024-06-18 12:50 UTC, benoit74 requested changes
Two small inline comments.

Regarding WebP support, I unfortunately cannot test it on my machines. And I'm not even sure I should. I've opened https://github.com/openzim/overview/issues/36 to discuss this topic openly, because I begin to consider we might be loosing our precious time with this WebP / WebM polyfills.

2024-06-19 02:10 UTC, dan-niles commented on zimui/src/views/VideoPlayerView.vue
> +  autoplay: false,
Created #233 to track this

2024-06-19 06:05 UTC, dan-niles commented on zimui/src/views/VideoPlayerView.vue
> +  playbackRates: [0.25, 0.5, 1, 1.5, 2],
For now, we'll be using `0.25, 0.5, 1, 1.5, 2` according to #174

2024-06-20 07:30 UTC, benoit74 approved these changes
LGTM, thank you!

2024-06-20 07:30 UTC, merged